baseURL = "https://srivpriyank-dev.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "a bit off"
theme = "cupper-hugo-theme"
enableGitInfo = true

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "Coder's Log"
  homeMetaContent = "11111110"
#  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."
 footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme)."  
# For more date formats see https://gohugo.io/functions/format/
  dateFormat = "May 5, 2019"
  katex = true

[menu]
  [[menu.nav]]
    name = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "blog"
    url = "/posts/"
    weight = 2
  [[menu.nav]]
    name = "tags"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "about"
    url = "/about/"
    weight = 4
 # [[menu.nav]]
 #   name = "RSS"
 #   url = "/index.xml"
 #   weight = 5
