baseURL = "https://priyank-sriv.github.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "'a bit off'"
theme = "beautifulhugo"
metaDataFormat = "yaml"
publishdir = "public"
paginate = 8
#googleAnalytics = "XXX"

[Params]
  caption = "\\ \\ \\ \\ \\ \\ \\ 0"
  logo = "images/logo.png" # Expecting square dimensions
  favicon = "favicon.ico"
  # dateFormat = "May 12, 2019"
  # comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  # delayDisqus = true
  # showRelatedPosts = true

[Author]
  name = "Priyank Srivastava"
  # email = "priyank.juggernaut@gmail.com"
  github = "priyank-sriv"
  linkedin = "sriv-priyank"
  # stackoverflow = "users/XXXXXXX/username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3
